SELECT T1.CAR_ID,
    T1.CAR_TYPE,
    ROUND(T1.DAILY_FEE * 30 * (100 - T2.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS T1
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS T2
        ON T1.CAR_TYPE = T2.CAR_TYPE AND T2.DURATION_TYPE = '30일 이상'
WHERE T1.CAR_TYPE IN ('세단', 'SUV')
    AND T1.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
    )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, T1.CAR_TYPE ASC, T1.CAR_ID DESC;