-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.PRICE*sum(o.AMOUNT) as 'TOTAL_SALES'
from FOOD_ORDER as o
LEFT JOIN  FOOD_PRODUCT as p ON p.PRODUCT_ID = o.PRODUCT_ID 
WHERE year(o.PRODUCE_DATE)=2022 AND month(o.PRODUCE_DATE)=5
GROUP BY 1
ORDER BY 3 desc, 1 asc;